# Use Java 21 (compatible with your app)
FROM eclipse-temurin:21-jdk

# Set working directory inside container
WORKDIR /app

# Copy the jar file into the container
COPY target/*.jar app.jar

# Expose the port Render will use
EXPOSE 8080

# Run the application
ENTRYPOINT ["java","-jar","/app/app.jar"]
